# Web Server
[server]
# Port for the web server
port = 1337
# IP for the web server
ip = "127.0.0.1"

# Included HTTP Proxy
[proxy]
# The proxy will not run if this is false
enabled = true
# Port for the proxy
port = 3003
# IP for the proxy
ip = "127.0.0.1"
# External Cert & Private key. If left blank, a new one will be generated and sent to stdout.
cert = ""
private_key = ""

[blocking]
# "all", "example" or "none"
# "example" blocks example.com and lets all other traffic through.
# THIS IS NOT FINISHED YET
mode = "all"